[target.xtensa-esp32s3-none-elf]
runner = "espflash flash -c esp32s3 -s 16mb -m dio -f 80mhz --no-skip --monitor"

[env]
ESP_LOG = "INFO"
ESP_HAL_PLACE_SPI_DRIVER_IN_RAM = "true"
ESP_HAL_CONFIG_PSRAM_MODE = "octal"
[build]
rustflags = ["-C", "link-arg=-nostartfiles"]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
