import { HorizontalBox, VerticalBox, Button, CheckBox, ScrollView } from "std-widgets.slint";

import { Theme, Toggle } from "common.slint";

export component AppWindow inherits Window {
    in-out property <string> text: "Please touch the button \nto update the PMU reading";
    in-out property <bool> charging: false;
    in property <image> status-icon: @image-url("../assets/battery.png");

    width: 536px;
    height: 240px;
    default-font-size: Theme.font-size-standard;
    callback request-update();
    callback toggle-charger(bool);

    HorizontalLayout {
        ScrollView {
            Text {
                text: root.text;
                font-size: Theme.font-size-small;
                wrap: TextWrap.word-wrap;
                horizontal-alignment: left;
                vertical-alignment: top;
            }
        }

        VerticalLayout {
            alignment: LayoutAlignment.start;
            padding: 10px;

            Image {
                source: root.status-icon;
                width: 40px;
                height: 40px;
            }

            Button {
                primary: true;
                text: "Update";
                width: 120px;
                height: 80px;
                clicked => {
                    root.request-update();
                }
            }

            Text {
                text: "Charging";
                font-size: Theme.font-size-standard;
            }

            Toggle {
                on: root.charging;
                clicked => {
                    root.toggle-charger(self.on);
                }
            }
        }
    }
}
