[package]
name = "slint-generated"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = { version = "1.11.0", default-features = false, features = [
    "libm",
    "unsafe-single-threaded",
    "compat-1-2",
    "renderer-software",
] }

[build-dependencies]
slint-build = "1.11.0"
