import { HorizontalBox, VerticalBox, Button } from "std-widgets.slint";
export component AppWindow inherits Window {
    in-out property <string> text: "Please click";
    in-out property <image> status-icon: @image-url("../assets/battery.png");
    default-font-size: 21px;
    callback request-update();

    HorizontalBox {

        Text {
            text: root.text;
        }

        VerticalBox {
            Image {
                source: root.status-icon;
                width: 64px;
                height: 64px;
            }

            HorizontalBox {
                Button {
                    accessible-role: AccessibleRole.checkbox;
                    primary: true;
                    text: "Update";
                    clicked => {
                        root.request-update();
                    }
                }
            }
        }
    }
}
