name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    env:
      MQTT_HOSTNAME: test.mosquitto.org
      MQTT_USERNAME: username
      MQTT_PASSWORD: password
      MQTT_PORT: 1883
      WIFI_SSID: ssid
      WIFI_PSK: password
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.7
        with:
          default: true
          buildtargets: esp32s3
          ldproxy: false
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.10
      - name: Run build
        run: cargo build --release
      - name: Run fmt
        run: cargo fmt --all -- --check --color always
      - name: Run clippy
        run: cargo clippy --all-features --workspace -- -D warnings
      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats